name: CSS + JS Minifaction + Obfuscation

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    tags:
      - '**'
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "minify"
  minify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v2

      - name: Auto Minify + Obfuscate src/Resources/Js
        # You may pin to the exact commit or the version.
        uses: nizarmah/auto-minify@v2.1.1
        with:
          directory: 'src/Resources/Js'
          overwrite: false
          js_engine: 'uglify-js'

      - name: Auto Minify src/Resources/Css
        # You may pin to the exact commit or the version.
        uses: nizarmah/auto-minify@v2.1.1
        with:
          directory: '*Components'
          overwrite: false

      - name: Auto Minify src/Resources/Css
        # You may pin to the exact commit or the version.
        uses: nizarmah/auto-minify@v2.1.1
        with:
          directory: 'src/Resources/Css'
          overwrite: false

      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ''
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
